In [ ]:
import pandas as pd

In [2]:
# ---------------------------------------------------------------
# Chargement des données
# ---------------------------------------------------------------

df = pd.read_parquet("/Users/matheoleroy/Downloads/data_nlp/legislatives_.parquet", engine="fastparquet")

# Normalisation des colonnes textuelles
df["date"] = df["date"].astype(str).str.strip()
if "party" in df.columns:
    df["party"] = df["party"].astype(str).str.upper().str.strip()

print(f"Corpus chargé : {df.shape[0]} documents, {df.shape[1]} colonnes.")
print("Colonnes :", list(df.columns))
df.head()

Corpus chargé : 12746 documents, 4 colonnes.
Colonnes : ['id', 'text', 'source', 'date']

,id,text,source,date
0,EL135_L_1981_06_062_11_1_PF_02,Sciences Po / fonds CEVIPOF\nCANDIDAT SUPPLEAN...,/home/onyxia/work/NLP_mini_project/text_files/...,1981
1,EL136_L_1981_06_067_05_1_PF_05,Sciences Po / fonds CEVIPOF\nElections Législa...,/home/onyxia/work/NLP_mini_project/text_files/...,1981
2,EL134_L_1981_06_035_01_1_PF_01,Sciences Po / fonds CEVIPOF\nElections législa...,/home/onyxia/work/NLP_mini_project/text_files/...,1981
3,EL135_L_1981_06_062_11_1_PF_01,ÉLECTIONS LÉGISLATIVES DU 14 JUIN 1981 - 11e C...,/home/onyxia/work/NLP_mini_project/text_files/...,1981
4,EL134_L_1981_06_021_04_1_PF_02,République Française\nELECTIONS LEGISLATIVES D...,/home/onyxia/work/NLP_mini_project/text_files/...,1981

In [4]:
metadata = pd.read_csv("/Users/matheoleroy/Downloads/data_nlp/archelect_search-2.csv")

metadata.head()

/var/folders/3k/gpr62wcn3h7dyfkv8l9fcsl00000gn/T/ipykernel_44140/3223142179.py:1: DtypeWarning: Columns (0: departement-nom, 1: departement-insee, 2: identifiant de circonscription, 3: pdf, 4: suppleant-nom, 5: suppleant-prenom, 6: suppleant-sexe, 7: suppleant-age, 8: suppleant-age-calcule, 9: suppleant-age-tranche, 10: suppleant-profession, 11: suppleant-mandat-en-cours, 12: suppleant-mandat-passe, 13: suppleant-associations, 14: suppleant-autres-statuts, 15: suppleant-soutien, 16: suppleant-liste, 17: suppleant-decorations) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv("/Users/matheoleroy/Downloads/data_nlp/archelect_search-2.csv")

,id,date,subject,title,contexte-election,contexte-tour,cote,departement,departement-nom,departement-insee,...,suppleant-age-calcule,suppleant-age-tranche,suppleant-profession,suppleant-mandat-en-cours,suppleant-mandat-passe,suppleant-associations,suppleant-autres-statuts,suppleant-soutien,suppleant-liste,suppleant-decorations
0,EL009_L_1958_11_001_01_1_PF_01,1958-11-23,France;Élections législatives;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,maire;conseiller général,non mentionné,non mentionné,non mentionné,Parti radical,non mentionné,non
1,EL009_L_1958_11_001_01_1_PF_02,1958-11-23,France;Ve République;Élections législatives;As...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,conseiller municipal,non mentionné,non mentionné,prisonnier de guerre,Union pour la nouvelle République,non mentionné,non
2,EL009_L_1958_11_001_01_1_PF_03,1958-11-23,Élections législatives;France;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste français,non mentionné,non
3,EL009_L_1958_11_001_01_1_PF_04,1958-11-23,Élections législatives;France;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,35,entre 30 et 39 ans,greffier de paix,conseiller municipal;conseiller général,non mentionné,non mentionné,combattant,non mentionné,non mentionné,oui
4,EL009_L_1958_11_001_01_1_PF_05,1958-11-23,Ve République;Assemblée Nationale;Élections lé...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur;président Coopérative élevage,non mentionné,non mentionné,non mentionné,non mentionné,Centre national des indépendants et paysans,non mentionné,non

In [9]:
metadata["titulaire-soutien"]

0                                            Parti radical
1                        Union pour la nouvelle République
2                                Parti communiste français
3                                            non mentionné
4              Centre national des indépendants et paysans
                               ...
33026    Europe écologie les Verts;Alliance écologiste ...
33027    Parti socialiste social-écologie;Place publiqu...
33028    La République en marche;Mouvement démocrate;Ag...
33029                 Union des démocrates et indépendants
33030    Les Républicains;Chasse pêche nature tradition...
Name: titulaire-soutien, Length: 33031, dtype: str

In [8]:
df_merged = df.merge(metadata, on="id", how="left", suffixes=("", "_meta"))
df_merged.to_parquet("/Users/matheoleroy/Downloads/data_nlp/legislatives_metadata.parquet", engine="fastparquet")